sudo: false
language: ruby
cache: bundler
rvm:
  - 2.3.1

script: bundle exec rspec

env:
  global:
    secure: klQ3BQNdKkGIq3Zfv8Sr6oZqaMg9GHx+LGhynQ5xt7A6SGvxbMuoXJlE9wW4me6u+B9S2D+q+pdKgGPE/+fHsVt/d0zDXRnrjVyo1eexT220AMfpjiFDAtya8sAcuuAICLhw8AmzTjns8yAWInv5U5vC6oejkLA71FXtHU//210=

matrix:
  include:
    - rvm: ree
      gemfile: gemfiles/ree.gemfile
      env: TEST_SUITE=spec

deploy:
  provider: rubygems
  api_key:
    secure: "c9QcNX+nk0Yzl22ZVknZtv+/G4fUeLph0TH9PS6hQ92zywM61wtXTJExZdBHulvKAaQbKaq20LcFjLw41qwJc6tvIEYXpOinfOaiemTKaGmKscDrIi3wUAxfjmTacXZAaTdEORQVqTOmppqsuKnP7cqmSNxTSI901Sz5Cy6Jpl0="
  on:
    tags: true
    repo: enova/business_calendar
